### ISSUE TITLE
Demo build failure

### ISSUE THREAD

**Issue by jlb6740** [gwihlidal/meshopt-rs#20]
Trying to run the example with this command:

`cargo run --release --example demo`

Here is the end of the error

> cargo:warning=c++: error: vendor/src/allocator.cpp: No such file or directory
> cargo:warning=c++: fatal error: no input files
> cargo:warning=compilation terminated.
> exit code: 1
> 
> --- stderr
> 
> 
> error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "src" "-Wall" "-Wextra" "-std=c++11" "-o" "/home/jlb6740/workloads/meshopt-rs/target/release/build/meshopt-1cbb12cbae4a23de/out/vendor/src/allocator.o" "-c" "vendor/src/allocator.cpp" with args "c++" did not execute successfully (status code exit code: 1).

**Comment by ConradBrean** [comment]
looks like you didn't clone vendor submodule
run git submodule update --init --recursive
