### ISSUE TITLE
Any plans for updating to newer versions of meshoptimizer library ?

### ISSUE THREAD

**Issue by Alekssasho** [gwihlidal/meshopt-rs#23]
I need newer API around meshlets from meshoptimizer library. Any plans to update the library or if not, would you accept a pull request for an update ?

**Comment by gwihlidal** [comment]
Hey Alekssasho, I've been super swamped with work. I'd be happy to take such a pull request.

**Comment by Alekssasho** [comment]
I have a first commit here https://github.com/Alekssasho/meshopt-rs/commit/68f48f71af964c8103a39383e56cc2bce4ca9afd, but have commented some of the code, and haven't fixed the examples. I am testing if everything works in my project and if so, I can fix the examples and the commented code and open a pull request
