### ISSUE TITLE
New release on crates.io

### ISSUE THREAD

**Issue by BeastLe9enD** [gwihlidal/meshopt-rs#30]
Hey, would be really neat to have a new crates.io release at some time :)

**Comment by Uriopass** [comment]
I just published [meshopt2](https://crates.io/crates/meshopt2) on crates.io, a forked version with all the pending pull requests (#29 #32 #33 #34) and the latest bindings. It comes with a small breaking change so I pushed it to 0.2.0

**Comment by Uriopass** [comment]
0.2.0 has been published for meshopt :)
