### ISSUE TITLE
Documentation coverage of the API

### ISSUE THREAD

**Issue by gwihlidal** [gwihlidal/meshopt-rs#4]
Many routines and types are missing code comments; this should be addressed.

**Comment by aredshaw** [comment]
Are you using REST APIs? If so, I might be able to help.
I would need to know the base path and endpoints.
Also, a list of possible methods and parameters.
And of course an API Key if one is required.

**Comment by gwihlidal** [comment]
Hi, there are no REST APIs in this case, just raw function calls. I have done a big documentation pass, so closing this issue now!
