### ISSUE TITLE
Properly publish v0.2.1 (and v0.2.0?) on github

### ISSUE THREAD

**Issue by oisyn** [gwihlidal/meshopt-rs#41]
I just published 0.2.1 on crates.io. It includes the `simplify_scale` by @BeastLe9enD and `simplify_with_locks` API functions

* https://github.com/gwihlidal/meshopt-rs/commit/5d243a89067b459b3b33a197ac94037d96963191
* https://github.com/gwihlidal/meshopt-rs/commit/4290a77896eb687533be510b58e28e256447ea82

I think we should do a proper release on github, but I noticed that we haven't done that for 0.2.0 either. What do you think, should we just ignore 0.2.0 or still do that for history's sake? :)

Either way, we need a good summary of all the changes. Is the changelog complete?

**Comment by oisyn** [comment]
Oh shoot, I just realized I forgot to update the version number in readme.md

**Comment by Uriopass** [comment]
Have done a proper release for latest version (0.4.0)
